name: Github Checkout Action
description: 'Checkout a repository with optional sparse-checkout'

inputs:
  repository:
    description: 'Repository to checkout'
    required: false
    default: ${{ github.repository }}
  ref:
    description: 'Ref to checkout'
    required: false
    default: ${{ github.event.ref }}
  sparse-checkout:
    description: 'Sparse checkout'
    required: false
  path:
    description: 'Path to checkout into'
    required: false
  token:
    description: 'Token to use for checkout'
    required: false

runs:
  using: 'composite'
  steps:
  - name: Checkout action
    run: |
      python3 -u ${{ github.action_path }}/main.py
    shell: bash
    env:
      CHECKOUT_REPOSITORY: ${{ inputs.repository }}
      CHECKOUT_REF: ${{ inputs.ref }}
      CHECKOUT_SPARSE: ${{ inputs.sparse-checkout }}
      CHECKOUT_PATH: ${{ inputs.path }}
      CHECKOUT_TOKEN: ${{ inputs.token }}
